### ISSUE TITLE
Exception in thread "JavaFX Application Thread"

### ISSUE THREAD

**Issue by alexandrebastien** [fiji/FilamentDetector#23]
Hi, I got this on a freshly downloaded version of Fiji (Win64):

```
[INFO] Running FilamentDetector version 1.0.0
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: de/biomedical_imaging/ij/steger/OverlapOption
	at sc.fiji.filamentdetector.detection.RidgeDetectionFilamentDetector.<init>(RidgeDetectionFilamentDetector.java:85)
	at sc.fiji.filamentdetector.detection.FilamentDetectorService.getDetectors(FilamentDetectorService.java:60)
	at sc.fiji.filamentdetector.gui.controller.DetectFilamentController.<init>(DetectFilamentController.java:183)
	at sc.fiji.filamentdetector.gui.controller.MainController.loadDetectFilament(MainController.java:336)
	at sc.fiji.filamentdetector.gui.controller.MainController$1.lambda$call$0(MainController.java:166)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: de.biomedical_imaging.ij.steger.OverlapOption
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```

I guess it's related with the J included JRE that might not contain JavaFX anymore... I'm not sure.

**Comment by alexandrebastien** [comment]
I also tested it with the new Java11 test [bundle](https://forum.image.sc/t/feedback-needed-bundled-java-future-directions/44030/5) and I got the same error.
